version: "3.9"
services:
  rivnegray_db:
    image: mysql:8.0.33-debian
    container_name: rivnegray_db
    ports:
      - "3326:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rivnegray_network

  rivnegray_server:
    image: tomcat:10.1.9-jre17
    container_name: rivnegray_server
    ports:
      - "8090:8080"
    volumes:
      - ./webapp:/usr/local/tomcat/webapps
    depends_on:
      - rivnegray_db
    networks:
      - rivnegray_network

volumes:
  db_data:

networks:
  rivnegray_network:
    driver: bridge


