version: "3"
services:
  rivnegray_db:
    image: mysql:latest
    container_name: rivnegray_db
    ports:
      - "3326:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  rivnegray_server:
    image: tomcat:latest
    container_name: rivnegray_server
    ports:
      - "8090:8080"
    volumes:
      - ./webapp:/usr/local/tomcat/webapps
    depends_on:
      - rivnegray_db

volumes:
  db_data:
