version: '3'
services:
  db:
    image: mysql:8.0.33-debian
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: shop
    restart: always

  app:
    image: gl0be/app:__TAG__

    ports:
      - "8080:8080"
    volumes:
      - ${VM_LOGS_PATH}:/app/logs
      - ${VM_IMAGES_PATH}:/app/images
    networks:
      - app-network
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      WAIT_HOSTS: db:3306
      SPRING_PROFILES_ACTIVE: dev-remote-VM
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
