spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3316/shop

server:
  port: 8085

springdoc:
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    path: /api/ui

logging:
  config: src/main/resources/logback-spring.xml
#logging:
#  level:
#    ua.rivnegray.boardgames_shop: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
#    org.springframework.security: DEBUG
---
spring:
  config:
    activate:
      on-profile: dev-local-dockerfile
  datasource:
    url: jdbc:mysql://db:3306/shop
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev-remote-AKS
  datasource:
    url: jdbc:mysql://db:3306/shop
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev-remote-VM
  datasource:
    url: jdbc:mysql://db:3306/shop
    username: root
    password: rvngr2023
server:
  port: 8080

