spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3316/shop

server:
  port: 8085
  error:
    include-message: always

springdoc:
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    path: /api/ui

custom:
  imagesDirectory: "/home/globe/rivnegray/images/"
  pageSize: 20
  baseImagesUrl: "/boardgames/images/"
  supportedImageExtensions:
    - ".jpg"
    - ".jpeg"
    - ".png"
---
spring:
  config:
    activate:
      on-profile: dev-local-dockerfile
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev-remote-AKS
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev-remote-VM
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: 8080

