spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
#      data-locations: static/startup.sql
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3316/shop

server:
  port: 8085

springdoc:
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    path: /api/ui

---
spring:
  config:
    activate:
      on-profile: dev-local-dockerfile
  datasource:
    url: jdbc:mysql://db:3306/shop
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev-remote-AKS
  datasource:
    url: jdbc:mysql://db:3306/shop
server:
  port: 8080
