spring:
  datasource:
    url: jdbc:mysql://localhost:3316/shop
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
#      schema-locations: data/init_database.sql

server:
  port: 8085


