spring:
  datasource:
    url: jdbc:mysql://db:3306/shop
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
#      schema-locations: data/init_database.sql

server:
  port: 8080


  # todo profiles for dev, prod
  # todo user startup script SQL to populate database
springdoc:
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    path: /api/ui

