openapi: 3.0.3
info:
  title: Boardgames
  version: 1.0.0
paths:
  /boardgames:
    get:
      summary: Get all boardgames
      operationId: getAllBoardGames
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BoardGameDto'
    post:
      summary: Add a new boardgame
      operationId: addBoardGame
      x-access-permission: boardGame:create
      security:
        - bearerAuth: []
      requestBody:
        description: Boardgame to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAndUpdateBoardGameDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardGameDto'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
  /boardgames/{id}:
    get:
      summary: Get a boardgame by id
      operationId: getBoardGameById
      parameters:
        - name: id
          in: path
          description: ID of the boardgame
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardGameDto'
        '404':
          description: Not Found
    put:
      summary: Update a boardgame
      operationId: updateBoardGame
      x-access-permission: boardGame:update
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the boardgame to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Boardgame to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAndUpdateBoardGameDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardGameDto'
        '404':
          description: Not Found
        '401':
          description: Unauthorized
    delete:
      summary: Delete a boardgame
      operationId: deleteBoardGame
      x-access-permission: boardGame:delete
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the boardgame to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '401':
          description: Unauthorized

  /boardgames/genres:
    get:
      summary: Get all genres
      operationId: getAllGenres
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BoardGameGenreDto'
    post:
      summary: Add a new genre
      operationId: addGenre
      x-access-permission: genreAndMechanic:create
      security:
        - bearerAuth: []
      requestBody:
        description: Genre to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAndUpdateBoardGameGenreDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardGameGenreDto'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized

  /boardgames/genres/{id}:
    get:
      summary: Get a genre by id
      operationId: getGenreById
      parameters:
        - name: id
          in: path
          description: ID of the genre
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardGameGenreDto'
        '404':
          description: Not Found
    put:
      summary: Update a genre
      operationId: updateGenre
      x-access-permission: genreAndMechanic:update
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          description: ID of the genre to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Genre to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAndUpdateBoardGameGenreDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardGameGenreDto'
        '404':
          description: Not Found
        '401':
          description: Unauthorized
    delete:
      summary: Delete a genre
      operationId: deleteGenre
      x-access-permission: genreAndMechanic:delete
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          description: ID of the genre to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '401':
          description: Unauthorized

  /boardgames/mechanics:
    get:
      summary: Get all mechanics
      operationId: getAllMechanics
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BoardGameMechanicDto'
    post:
      summary: Add a new mechanic
      operationId: addMechanic
      x-access-permission: genreAndMechanic:create
      security:
        - bearerAuth: [ ]
      requestBody:
        description: Mechanic to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAndUpdateBoardGameMechanicDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardGameMechanicDto'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized

  /boardgames/mechanics/{id}:
    get:
      summary: Get a mechanic by id
      operationId: getMechanicById
      parameters:
        - name: id
          in: path
          description: ID of the mechanic
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardGameMechanicDto'
        '404':
          description: Not Found
    put:
      summary: Update a mechanic
      operationId: updateMechanic
      x-access-permission: genreAndMechanic:update
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          description: ID of the mechanic to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Mechanic to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAndUpdateBoardGameMechanicDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardGameMechanicDto'
        '404':
          description: Not Found
        '401':
          description: Unauthorized
    delete:
      summary: Delete a mechanic
      operationId: deleteMechanic
      x-access-permission: genreAndMechanic:delete
      security:
        - bearerAuth: [ ]
      parameters:
        - name: id
          in: path
          description: ID of the mechanic to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '401':
          description: Unauthorized
  /boardgames/filter/:
#    todo might need to change to get method with query params
    post:
      summary: filter boardgames
      operationId: filterBoardGames
      requestBody:
        description: map of filter properties with their values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilterBoardGamesRequestDto'
      responses:
        '200':
          description: Filtered successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BoardGameDto'

  /boardgames/search/{searchValue}:
    get:
      summary: search
      operationId: searchBoardgames
      parameters:
        - name: searchValue
          in: path
          description: search value for performing search on boardgames
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BoardGameDto'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
#    FilterBoardGamesRequestDto:
#      type: object
#      properties:
#        filters:
#          type: object
#          additionalProperties:
#            type: array
#            items:
#              type: string
#      required:
#        - filters
    FilterBoardGamesRequestDto:
      type: object
      properties:
        manufacturers:
          type: array
          items:
            type: string
        minProductPrice:
          type: number
          format: float
        maxProductPrice:
          type: number
          format: float
        boardGameGenres:
          type: array
          items:
            type: string
        boardGameMechanics:
          type: array
          items:
            type: string
        minAges:
          type: array
          items:
            type: integer
        playerCounts:
          type: array
          items:
            type: integer
        minGameDuration:
          type: integer
        maxGameDuration:
          type: integer
        boardGameLanguages:
          type: array
          items:
            $ref: '#/components/schemas/BoardGameLanguage'
    BoardGameDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        dateCreated:
          type: string
          format: date-time
        dateUpdated:
          type: string
          format: date-time
        isRemoved:
          type: boolean
        Manufacturer:
          type: string
        productName:
          type: string
        productDescription:
          type: string
        productPrice:
          type: number
          format: float
        productQuantityInStock:
          type: integer
          format: int32
        productImageURL:
          type: string
        productCategory:
          $ref: '#/components/schemas/ProductCategory'
        productCode:
          type: string
        gameSet:
          type: string
        gameGenreGenreNames:
          type: array
          items:
            type: string
        gameMechanicMechanicNames:
          type: array
          items:
            type: string
        minAge:
          type: integer
          format: int32
        minPlayers:
          type: integer
          format: int32
        maxPlayers:
          type: integer
          format: int32
        minGameDuration:
          type: integer
        maxGameDuration:
          type: integer
        gameLanguage:
          $ref: '#/components/schemas/BoardGameLanguage'
        BGGLink:
          type: string
          format: uri
      required:
        - id
        - dateCreated
        - dateUpdated
        - isRemoved
        - Manufacturer
        - productName
        - productPrice
        - productQuantityInStock
        - productCategory

    CreateAndUpdateBoardGameDto:
      type: object
      properties:
        manufacturer:
          type: string
        productName:
          type: string
        productDescription:
          type: string
        productPrice:
          type: string
          format: decimal
        productQuantityInStock:
          type: integer
        productImageURL:
          type: string
        productCategory:
          $ref: '#/components/schemas/ProductCategory'
        productCode:
          type: string
        gameSet:
          type: string
        gameGenreIds:
          type: array
          items:
            type: integer
            format: int64
          example: [ 1 ]
        gameMechanicIds:
          type: array
          items:
            type: integer
            format: int64
          example: [ 1 ]
        minAge:
          type: integer
        minPlayers:
          type: integer
        maxPlayers:
          type: integer
        minGameDuration:
          type: integer
        maxGameDuration:
          type: integer
        gameLanguage:
          $ref: '#/components/schemas/BoardGameLanguage'
        BGGLink:
          type: string
          format: url
          example: https://boardgamegeek.com/boardgame/169786/pandemic-legacy-season-1
      required:
        - manufacturer
        - productName
        - productPrice
        - productQuantityInStock
        - productImageURL
        - productCategory
        - productCode
        - gameSet
        - gameGenreGenreNames
        - gameMechanicMechanicNames
        - minAge
        - minPlayers
        - gameDuration
        - gameLanguage
        - BGGLink

    BoardGameLanguage:
      type: string
      enum: [ ENGLISH, RUSSIAN, UKRAINIAN, OTHER ]

    ProductCategory:
      type: string
      enum: [ BOARD_GAMES, ACCESSORIES, OTHER ]

    BoardGameGenreDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        genreName:
          type: string
        genreDescription:
          type: string

    CreateAndUpdateBoardGameGenreDto:
      type: object
      properties:
        genreName:
          type: string
        genreDescription:
          type: string

    BoardGameMechanicDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        mechanicName:
          type: string
        mechanicDescription:
          type: string

    CreateAndUpdateBoardGameMechanicDto:
      type: object
      properties:
        mechanicName:
          type: string
        mechanicDescription:
          type: string
    
