openapi: 3.0.3
info:
  title: Boardgames
  version: 1.0.0
paths:
  /boardgames:
    get:
      summary: Get all boardgames
      operationId: getAllBoardGames
      x-acess-permission: user:read
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BoardGameDto'
    post:
      summary: Add a new boardgame
      operationId: addBoardGame
      x-acess-permission: admin:write
      requestBody:
        description: Boardgame to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBoardGameDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardGameDto'
        '400':
          description: Bad Request
  /boardgames/{id}:
    get:
      summary: Get a boardgame by id
      operationId: getBoardGameById
      x-acess-permission: user:read
      parameters:
        - name: id
          in: path
          description: ID of the boardgame
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardGameDto'
        '404':
          description: Not Found
    put:
      summary: Update a boardgame
      operationId: updateBoardGame
      x-acess-permission: admin:write
      parameters:
        - name: id
          in: path
          description: ID of the boardgame to update
          required: true
          schema:
            type: integer
      requestBody:
        description: Boardgame to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoardGameDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardGameDto'
        '404':
          description: Not Found
    delete:
      summary: Delete a boardgame
      operationId: deleteBoardGame
      x-acess-permission: admin:write
      parameters:
        - name: id
          in: path
          description: ID of the boardgame to delete
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
components:
  schemas:
    BoardGameDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        dateCreated:
          type: string
          format: date-time
        dateUpdated:
          type: string
          format: date-time
        isRemoved:
          type: boolean
        Manufacturer:
          type: string
        productName:
          type: string
        productDescription:
          type: string
        productPrice:
          type: number
          format: float
        productQuantityInStock:
          type: integer
          format: int32
        productImageURL:
          type: string
        productCategory:
          $ref: '#/components/schemas/ProductCategory'
        productCode:
          type: string
        gameSet:
          type: string
        gameGenreGenreNames:
          type: array
          items:
            type: string
        gameMechanicMechanicNames:
          type: array
          items:
            type: string
        minAge:
          type: integer
          format: int32
        minPlayers:
          type: integer
          format: int32
        gameDuration:
          type: string
        gameLanguage:
          $ref: '#/components/schemas/BoardGameLanguage'
        BGGLink:
          type: string
          format: uri
      required:
        - id
        - dateCreated
        - dateUpdated
        - isRemoved
        - Manufacturer
        - productName
        - productPrice
        - productQuantityInStock
        - productCategory

    CreateBoardGameDto:
      type: object
      properties:
        Manufacturer:
          type: string
        productName:
          type: string
        productDescription:
          type: string
        productPrice:
          type: string
          format: decimal
        productQuantityInStock:
          type: integer
        productImageURL:
          type: string
        productCategory:
          $ref: '#/components/schemas/ProductCategory'
        productCode:
          type: string
        gameSet:
          type: string
        gameGenreGenreNames:
          type: array
          items:
            type: string
        gameMechanicMechanicNames:
          type: array
          items:
            type: string
        minAge:
          type: integer
        minPlayers:
          type: integer
        gameDuration:
          type: string
        gameLanguage:
          $ref: '#/components/schemas/BoardGameLanguage'
        BGGLink:
          type: string
          format: url
      required:
        - Manufacturer
        - productName
        - productPrice
        - productQuantityInStock
        - productImageURL
        - productCategory
        - productCode
        - gameSet
        - gameGenreGenreNames
        - gameMechanicMechanicNames
        - minAge
        - minPlayers
        - gameDuration
        - gameLanguage
        - BGGLink

    BoardGameLanguage:
      type: string
      enum: [ ENGLISH, RUSSIAN, UKRAINIAN, OTHER ]

    ProductCategory:
      type: string
      enum: [ BOARD_GAMES, ACCESSORIES, OTHER ]
    
