openapi: 3.0.3
info:
  title: Board Game Shopping API
  description: API for a board game shopping page
  version: 1.0.0
servers:
  - url: http://localhost:8085
paths:
  /games:
    get:
      summary: Get a list of board games
      operationId: getGames
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
    post:
      summary: Add a new board game
      operationId: addGame
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewGame'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  /games/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Get a board game by ID
      operationId: getGameById
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
    put:
      summary: Update a board game by ID
      operationId: updateGameById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatedGame'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
    delete:
      summary: Delete a board game by ID
      operationId: deleteGameById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Successful operation
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
    NewGame:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
    UpdatedGame:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
