openapi: 3.0.3
info:
  title: FavouritesAPI
  description: FavouritesAPI
  version: 1.0.0
paths:
  /favourites/map:
    post:
      summary: Map favourites from one stored in local storage to one stored in database
      operationId: mapFavourites
      x-access-permission: user:updateMe
      description: "This operation is used when a user decides to log in or register.
       Mapping of favourites from local storage to database should occur automatically upon login."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MapProductInFavouritesDto'
      responses:
        '200':
          description: Favourites mapped successfully
        '400':
          description: Invalid favourites data
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

components:
  schemas:
    MapProductInFavouritesDto:
      type: object
      properties:
        emptyValue:
          type: string