# todo separate address api from user api
openapi: 3.0.3
info:
  title: User API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      operationId: getAllUsersPublicInfo
      x-acess-permission: admin:read
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserPublicDto'
    post:
      summary: Create a new user with specified roles
      operationId: createSpecifiedUser
      x-acess-permission: admin:write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAnyUserDto'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPublicDto'
  /users/customer:
    post:
      summary: Create a new customer user
      operationId: createCustomerUser
      x-acess-permission:  user:write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerUserDto'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPublicDto'
  /users/{userId}:
    get:
      summary: Get a user by ID
      operationId: getUserPublicInfoById
      x-acess-permission: admin:read
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPublicDto'
        '404':
          description: User not found
    delete:
      summary: Delete a user by ID
      operationId: deleteUser
      x-acess-permission: admin:write
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: User deleted
        '404':
          description: User not found
  /users/{userId}/username:
    patch:
      summary: Update a user's username
      operationId: updateUsername
      x-acess-permission: user:write
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUsernameDto'
      responses:
        '200':
          description: username updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPublicDto'
  /users/{userId}/password:
    patch:
      summary: Update a user's password
      operationId: updatePassword
      x-acess-permission: user:write
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePasswordDto'
      responses:
        '200':
          description: password updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPublicDto'
  /users/{userId}/email:
    patch:
      summary: Update a user's email
      operationId: updateEmail
      x-acess-permission: user:write
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmailDto'
      responses:
        '200':
          description: email updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPublicDto'
  /users/{userId}/phone:
    patch:
      summary: Update a user's phone
      operationId: updatePhone
      x-acess-permission: user:write
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePhoneDto'
      responses:
        '200':
          description: phone number updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPublicDto'
  /users/{userId}/address:
    post:
      summary: Add an address to a user
      operationId: addAddress
      x-acess-permission: user:write
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddAndUpdateAddressDto'
      responses:
        '201':
          description: address added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPublicDto'
  /users/{userId}/address/{addressId}:
    patch:
      summary: Update a user's address
      operationId: updateAddress
      x-acess-permission: user:write
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: addressId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddAndUpdateAddressDto'
      responses:
        '200':
          description: address updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPublicDto'
    delete:
      summary: Remove an address from a user
      operationId: removeAddress
      x-acess-permission: user:write
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: addressId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: address deleted
        '404':
          description: address not founf
  /users/role/{role}:
    get:
      summary: Get users by role
      operationId: getUsersByRole
      x-acess-permission: admin:read
      parameters:
        - in: path
          name: role
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Users wih role found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserPublicDto'
  /users/roles:
    get:
      summary: Get all user roles
      operationId: getAllUserRoles
      x-acess-permission: admin:read
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserRoleDto'

  /users/availability/email:
    post:
      summary: Check if email is available
      operationId: checkEmailAvailability
      x-acess-permission: admin:read
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmailDto'
      responses:
        '204':
          description: checked for availability of email successfully
          content:
            application/json:
              schema:
                type: boolean
        '409':
          description: email already taken
          content:
            application/json:
              schema:
                type: boolean
  /users/availability/username:
    post:
      summary: Check if username is available
      operationId: checkUsernameAvailability
      x-acess-permission: admin:read
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUsernameDto'
      responses:
        '204':
          description: checked for availability of username successfully
          content:
            application/json:
              schema:
                type: boolean
        '409':
          description: username already taken
          content:
            application/json:
              schema:
                type: boolean
  /users/{userId}/addresses/{addressId}:
    get:
      summary: Get a user's address by address id
      operationId: getAddressById
      x-acess-permission: user:read
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: addressId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The address was found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressDto'
  /users/{userId}/addresses:
    get:
      summary: Get all addresses of a user
      operationId: getAllAddresses
      x-acess-permission: user:read
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: All addresses were retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AddressDto'
components:
  schemas:
    CreateAnyUserDto:
      x-java-type: ua.rivnegray.boardgames_shop.DTO.request.create.CreateAnyUserDto
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        roleIds:
          type: array
          items:
            type: integer
            format: int64
        email:
          type: string
        phone:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    CreateCustomerUserDto:
      type: object
      x-java-type: ua.rivnegray.boardgames_shop.DTO.request.create.CreateCustomerUserDto
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
        phone:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    UpdateEmailDto:
      type: object
      x-java-type: ua.rivnegray.boardgames_shop.DTO.request.update.UpdateEmailDto
      properties:
        email:
          type: string
    UpdateFullUserProfileDto:
      type: object
      x-java-type: ua.rivnegray.boardgames_shop.DTO.request.update.UpdateFullUserProfileDto
      properties:
        email:
          type: string
        phone:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    UpdatePasswordDto:
      type: object
      x-java-type: ua.rivnegray.boardgames_shop.DTO.request.update.UpdatePasswordDto
      properties:
        password:
          type: string
    UpdatePhoneDto:
      type: object
      x-java-type: ua.rivnegray.boardgames_shop.DTO.request.update.UpdatePhoneDto
      properties:
        phone:
          type: string
    UpdateRolesDto:
      type: object
      x-java-type: ua.rivnegray.boardgames_shop.DTO.request.update.UpdateRolesDto
      properties:
        roleIds:
          type: array
          items:
            type: integer
            format: int64
    UpdateUsernameDto:
      type: object
      x-java-type: ua.rivnegray.boardgames_shop.DTO.request.update.UpdateUsernameDto
      properties:
        username:
          type: string
    AddAndUpdateAddressDto:
      type: object
      x-java-type: ua.rivnegray.boardgames_shop.DTO.request.AddAndUpdateAddressDto
      properties:
        street:
          type: string
        houseNumber:
          type: string
        postalCode:
          type: string
        city:
          type: string
        country:
          type: string
    AddressDto:
      type: object
      x-java-type: ua.rivnegray.boardgames_shop.DTO.response.AddressDto
      properties:
        id:
          type: integer
          format: int64
        street:
          type: string
        houseNumber:
          type: string
        postalCode:
          type: string
        city:
          type: string
        country:
          type: string
    UserProfileDto:
      type: object
      x-java-type: ua.rivnegray.boardgames_shop.DTO.response.UserProfileDto
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        phone:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    UserPublicDto:
      type: object
      x-java-type: ua.rivnegray.boardgames_shop.DTO.response.UserPublicDto
      properties:
        username:
          type: string
        roles:
          type: array
          items:
            $ref: '#/components/schemas/UserRoleDto'
        email:
          type: string
        phone:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/AddressDto'
    UserRoleDto:
      type: object
      x-java-type: ua.rivnegray.boardgames_shop.DTO.response.UserRoleDto
      properties:
        id:
          type: integer
          format: int64
        roleName:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/UserPermission'
    UserPermission:
      type: string
      x-java-type: ua.rivnegray.boardgames_shop.model.user.UserPermission
      enum:
        - user:read
        - user:write
        - admin:read
        - admin:write

