package ua.rivnegray.boardgames_shop.DTO.response;

import io.swagger.v3.oas.annotations.media.Schema;

public record TokenDto(
        @Schema(
                example = "eyJraWQiOiI2NzNkNzRmNi0zY2M1LTRjM2YtYjliOS04ZDg5ZDcyNTFkNGIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInNjb3BlIjpbImdlbnJlQW5kTWVjaGFuaWM6Y3JlYXRlIiwiYm9hcmRHYW1lOmRlbGV0ZSIsInVzZXI6ZGVsZXRlIiwidXNlcjp1cGRhdGVNZSIsInVzZXI6cmVhZE1lIiwib3JkZXI6ZXhwb3J0Iiwib3JkZXI6cmVhZCIsImJvYXJkR2FtZTphcmNoaXZlQW5kVW5hcmNoaXZlIiwidXNlcjp1cGRhdGUiLCJzaG9wcGluZ0NhcnQ6bWFuYWdlTWUiLCJvcmRlcjpjcmVhdGUiLCJib2FyZEdhbWU6dXBkYXRlIiwiZ2VucmVBbmRNZWNoYW5pYzpkZWxldGUiLCJnZW5yZUFuZE1lY2hhbmljOnVwZGF0ZSIsIm9yZGVyOmRlbGV0ZSIsInVzZXI6Y3JlYXRlIiwib3JkZXI6dXBkYXRlU3RhdHVzIiwiYm9hcmRHYW1lOmNyZWF0ZSIsInVzZXI6cmVhZCIsImJvYXJkR2FtZTpyZWFkQXJjaGl2ZWQiLCJvcmRlcjpyZWFkTWUiLCJvcmRlcjpjYW5jZWxNZSIsInNob3BwaW5nQ2FydDpyZWFkIl0sImlzcyI6InNlbGYiLCJpZCI6MSwiZXhwIjoxNjk1NjQ3ODY2LCJpYXQiOjE2OTU2NDQyNjZ9.Iu5X-L06FpWSvrjAMpNMjeaGAoZHgpeAozFTWpT6KDtHZTc2UXQc1ZANiuEYa5-RruBY5BjP5qScNMDrJJzaaHJZ-99xh8tCD0Fb7A3gXyLZwxT8uaHeU323QaNfNo9Y6HwHBUzh-zwPkLG5OhXMi90jUj5WyMuF8sKqgF92lrIDMwOeopW0TSptPHhvkJnPY0kmTSNrLSssnpgigoSubvKxKRxV_TEbagzVuvwwJPBLGHamBCyBSDc9-2OMBU7_MCSbjT53OPj7b5GstcBTI0xJo-hvUgSMyjRenoL9CYbliMU1CtNSbHsqa0l-W8KiM94HTP8ZthAy1OjnwINBgA"
        )
        String tokenValue) {
}
