name: Deploy to VM

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: your-dockerhub-username/your-app:latest  # replace with your Docker Hub username and app name
#
#      - name: Set up SSH
#        uses: webfactory/ssh-agent@v0.5.2
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#
#      - name: Deploy to VM
#        run: |
#          ssh username@your-vm-ip "docker pull your-dockerhub-username/your-app:latest && docker-compose up -d"

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Execute command via SSH
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.VM_HOST }}
            username: ${{ secrets.VM_USERNAME }}
            key: ${{ secrets.VM_PRIVATE_KEY }}
            script: ls -la

