name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile-app
          push: true
          tags: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/app:latest

      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: containers
          name: rivnegraycontainers
          image: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/app:latest
          registry-login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          location: 'northeurope'
          dns-name-label: rivnegraycontainers
