name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-app
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/app:latest

      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource_group: containers
          name: rivnegraycontainers
          image: ${{ secrets.ACR_LOGIN_SERVER }}/app:latest
          registry_login_server: ${{ secrets.ACR_LOGIN_SERVER }}
          registry_username: ${{ secrets.ACR_USERNAME }}
          registry_password: ${{ secrets.ACR_PASSWORD }}
          location: northeurope
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
