name: Deploy to AKS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az version

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/app:${{ github.sha }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: rivnegray-AKS
          resource-group: rivnegray-AKS-resource-group

      - name: Install and set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Replace image references
        run: |
          sed -i 's/${TAG}/${{ github.sha }}/g' ./k8s/app-deployment.yaml

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            ./k8s/app-deployment.yaml
            ./k8s/app-service.yaml
            ./k8s/boardgames-shop-app-network-networkpolicy.yaml
            ./k8s/db-data-persistentvolumeclaim.yaml
            ./k8s/db-deployment.yaml
            ./k8s/db-service.yaml
